"use client";
import { motion } from "framer-motion";

export default function YearComponent() {
  return (
    <div className="flex flex-col items-center w-full h-full mt-10 gap-8">
      <motion.h1
        className="text-7xl text-center"
        initial={{ opacity: 0, y: -50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        Feliz 1 ano meu <br /><span>amorzim</span>
      </motion.h1>

      <div className="flex items-center">
        <div className="w-full">
          <motion.h1
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1, delay: 0.3 }}
            className="text-xl"
          >
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
          </motion.h1>
        </div>
        <div className="h-full w-2/3 flex justify-center">
          <motion.img
            src="/images/Altar.jpg"
            alt="Altar"
            className="w-[80%] h-full object-cover rounded-full shadow-[5px_10px_15px_rgba(255,105,180,0.6)]"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1, delay: 0.5 }}
          />
        </div>
      </div>

      <div className="flex items-center justify-center">
        <div className="h-full w-2/3 flex justify-center">
          <motion.img
            src="/images/HomephotoTalit2.jpg"
            alt="Home"
            className="w-[80%] h-full object-cover rounded-full shadow-[5px_10px_15px_rgba(255,105,180,0.6)]"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1, delay: 0.7 }}
          />
        </div>
        <div className="w-full">
          <motion.h1
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1, delay: 0.3 }}
            className="text-xl"
          >
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
            Lorem ipsum dolor sit amet consectetur adipisicing elit...
          </motion.h1>
        </div>
      </div>
    </div>
  );
}